inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/application.rb'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'spec/rails_helper'
    - 'spec/spec_helper'
    - 'Guardfile'
    - 'node_modules/**/*'
    - '**/*.arb'
    - '**/*.axlsx'


inherit_from:
  - .rubocop_rspec.yml
  - .rubocop_metrics.yml
  - .rubocop_layout.yml
  - .rubocop_lint.yml
  - .rubocop_naming.yml
  - .rubocop_rails.yml
  - .rubocop_style.yml
