# Don't use assignment in conditions
Lint/AssignmentInCondition:
  AllowSafeAssignment: false

# This cop checks for ambiguous operators in the first argument of a method invocation without parentheses.
Lint/AmbiguousOperator:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

# Suppressing exceptions can be perfectly fine, and be it to avoid to
# explicitly type nil into the rescue since that's what you want to return,
# or suppressing LoadError for optional dependencies
Lint/SuppressedException:
  Enabled: false

# Shadowing outer local variables with block parameters is often useful
# to not reinvent a new name for the same thing, it highlights the relation
# between the outer variable and the parameter. The cases where it's actually
# confusing are rare, and usually bad for other reasons already, for example
# because the method is too long.
Lint/ShadowingOuterLocalVariable:
  Enabled: false

# There are valid cases, for example debugging Cucumber steps,
# also they'll fail CI anyway. Then add those files to exclude
Lint/Debugger:
  Enabled: true

# Inherit errors from StandardError is more typical than from RuntimeError
Lint/InheritException:
  EnforcedStyle: standard_error

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true
